/* Shared mock data for /marketplace and /profile demos */
window.MARKETPLACE_DATA = {
  brand: [
    { id: "liquid-iv",     title: "Liquid I.V.",     img: "https://placehold.co/96x96/2196f3/fff?text=L",  cats: ["Health","DTC"],         desc: "Hydration multiplier brand running on Health, Sports and Performance shows.",                metrics: { roas: "4.1x", spend: "$612K", shows: "38"  } },
    { id: "ag1",           title: "Athletic Greens", img: "https://placehold.co/96x96/0d6832/fff?text=AG", cats: ["Health","Wellness"],    desc: "AG1 — daily greens product with one of the largest host-read footprints in podcasting.",     metrics: { roas: "3.8x", spend: "$2.1M", shows: "112" } },
    { id: "magic-spoon",   title: "Magic Spoon",     img: "https://placehold.co/96x96/6a1b9a/fff?text=MS", cats: ["Food","DTC"],           desc: "Low-carb cereal brand. Heavy spend in Comedy and Lifestyle.",                                  metrics: { roas: "3.2x", spend: "$390K", shows: "22"  } },
    { id: "helix",         title: "Helix Sleep",     img: "https://placehold.co/96x96/1a252f/fff?text=H",  cats: ["Sleep","Home"],         desc: "Mattress brand with a deep history in podcast direct response.",                              metrics: { roas: "2.9x", spend: "$840K", shows: "54"  } },
    { id: "ziprecruiter",  title: "ZipRecruiter",    img: "https://placehold.co/96x96/0e1323/fff?text=ZR", cats: ["B2B","SaaS"],           desc: "One of the longest-running podcast advertisers. Broad multi-category buy.",                   metrics: { roas: "2.4x", spend: "$3.4M", shows: "180" } },
    { id: "squarespace",   title: "Squarespace",     img: "https://placehold.co/96x96/000/fff?text=SQ",    cats: ["SaaS","Creator"],       desc: "Website builder. Common across Comedy, Tech and Creator-economy shows.",                      metrics: { roas: "2.6x", spend: "$2.8M", shows: "164" } },
    { id: "seed",          title: "Seed Health",     img: "https://placehold.co/96x96/16a085/fff?text=SH", cats: ["Health","DTC"],         desc: "DS-01 daily synbiotic. Wellness, Performance and Longevity shows.",                           metrics: { roas: "3.5x", spend: "$280K", shows: "31"  } },
    { id: "manscaped",     title: "Manscaped",       img: "https://placehold.co/96x96/c0392b/fff?text=MN", cats: ["Personal Care"],        desc: "Below-the-belt grooming brand. Strong in Sport and Comedy.",                                  metrics: { roas: "3.0x", spend: "$510K", shows: "44"  } },
    { id: "betterhelp",    title: "BetterHelp",      img: "https://placehold.co/96x96/27ae60/fff?text=BH", cats: ["Health","Mental"],      desc: "Online therapy. Largest single host-read advertiser on podcasts.",                            metrics: { roas: "2.2x", spend: "$5.1M", shows: "240" } },
    { id: "factor",        title: "Factor",          img: "https://placehold.co/96x96/e67e22/fff?text=FA", cats: ["Food","DTC"],           desc: "Prepared meals. Expanding on Health, Performance and Sport shows.",                           metrics: { roas: "3.1x", spend: "$720K", shows: "62"  } },
    { id: "rocketmoney",   title: "Rocket Money",    img: "https://placehold.co/96x96/8e44ad/fff?text=RM", cats: ["Fintech","App"],        desc: "Subscription canceller and personal finance app.",                                            metrics: { roas: "2.7x", spend: "$1.2M", shows: "98"  } },
    { id: "aura",          title: "Aura",            img: "https://placehold.co/96x96/2c3e50/fff?text=AU", cats: ["Security","App"],       desc: "Identity theft protection. Commonly bundled with True Crime audiences.",                      metrics: { roas: "2.5x", spend: "$640K", shows: "55"  } },
  ],
  show: [
    { id: "jre",           title: "The Joe Rogan Experience",   img: "https://placehold.co/96x96/0d0d0d/fff?text=JRE", cats: ["Society","Comedy"],         desc: "The largest podcast in the world. Long-form interviews across science, politics and comedy.", metrics: { listeners: "11M+", cpm: "$45", advertisers: "62" } },
    { id: "huberman",      title: "Huberman Lab",               img: "https://placehold.co/96x96/2980b9/fff?text=HL",  cats: ["Health","Science"],         desc: "Andrew Huberman on neuroscience and protocols for performance, sleep and longevity.",         metrics: { listeners: "5.2M", cpm: "$58", advertisers: "28" } },
    { id: "daily-stoic",   title: "Daily Stoic",                img: "https://placehold.co/96x96/c0392b/fff?text=DS",  cats: ["Health","Philosophy"],      desc: "Ryan Holiday on stoic philosophy applied to modern life. High-intent wellness audience.",     metrics: { listeners: "323K", cpm: "$38", advertisers: "14" } },
    { id: "crime-junkie",  title: "Crime Junkie",               img: "https://placehold.co/96x96/1a252f/fff?text=CJ",  cats: ["True Crime"],               desc: "Top-charting true crime show with one of the most engaged audiences in podcasting.",          metrics: { listeners: "450K", cpm: "$42", advertisers: "19" } },
    { id: "smartless",     title: "SmartLess",                  img: "https://placehold.co/96x96/16a085/fff?text=SL",  cats: ["Comedy","Society"],         desc: "Will Arnett, Jason Bateman, Sean Hayes interview unannounced guests.",                         metrics: { listeners: "380K", cpm: "$51", advertisers: "16" } },
    { id: "mfm",           title: "My Favorite Murder",         img: "https://placehold.co/96x96/c0392b/fff?text=MF",  cats: ["Comedy","True Crime"],      desc: "Karen Kilgariff and Georgia Hardstark cover true crime with a comedic lens.",                  metrics: { listeners: "310K", cpm: "$39", advertisers: "12" } },
    { id: "tim-ferriss",   title: "The Tim Ferriss Show",       img: "https://placehold.co/96x96/8e44ad/fff?text=TF",  cats: ["Business","Health"],        desc: "Tim Ferriss interviews world-class performers on tactics, routines and habits.",              metrics: { listeners: "290K", cpm: "$48", advertisers: "21" } },
    { id: "call-her-daddy",title: "Call Her Daddy",             img: "https://placehold.co/96x96/e91e63/fff?text=CD",  cats: ["Society","Health"],         desc: "Alex Cooper. Bold conversations on relationships and modern womanhood.",                        metrics: { listeners: "323K", cpm: "$44", advertisers: "18" } },
    { id: "new-heights",   title: "New Heights",                img: "https://placehold.co/96x96/2ecc71/fff?text=NH",  cats: ["Sport","Comedy"],           desc: "Jason and Travis Kelce on NFL life, family and pop culture.",                                   metrics: { listeners: "323K", cpm: "$52", advertisers: "15" } },
    { id: "on-purpose",    title: "On Purpose",                 img: "https://placehold.co/96x96/9c27b0/fff?text=OP",  cats: ["Health","Society"],         desc: "Jay Shetty on mindfulness, purpose and habits.",                                                metrics: { listeners: "323K", cpm: "$36", advertisers: "11" } },
    { id: "conan",         title: "Conan O'Brien Needs a Friend",img: "https://placehold.co/96x96/e67e22/fff?text=CO", cats: ["Comedy"],                   desc: "Conan tries to befriend his comedy heroes and famous strangers.",                               metrics: { listeners: "420K", cpm: "$46", advertisers: "20" } },
    { id: "armchair",      title: "Armchair Expert",            img: "https://placehold.co/96x96/27ae60/fff?text=AE",  cats: ["Society"],                  desc: "Dax Shepard interviews experts and celebrities on the messiness of being human.",              metrics: { listeners: "275K", cpm: "$41", advertisers: "13" } },
  ],
  industry: [
    { id: "health",        title: "Health & Wellness",   img: "https://placehold.co/96x96/0d6832/fff?text=H%26W", cats: ["DTC","Supplements"], desc: "DTC supplements, fitness and longevity. Largest host-read category by spend.",            metrics: { advertisers: "184", shows: "612", avgRoas: "3.8x" } },
    { id: "fintech",       title: "Fintech",             img: "https://placehold.co/96x96/8e44ad/fff?text=FN",     cats: ["B2C","App"],         desc: "Trading, neo-banks, budgeting and crypto apps.",                                            metrics: { advertisers: "78",  shows: "224", avgRoas: "2.6x" } },
    { id: "b2b-saas",      title: "B2B SaaS",            img: "https://placehold.co/96x96/0e1323/fff?text=B2B",    cats: ["SaaS"],              desc: "Sales tooling, dev tools, marketing and analytics platforms.",                              metrics: { advertisers: "94",  shows: "168", avgRoas: "2.1x" } },
    { id: "food-beverage", title: "DTC Food & Beverage", img: "https://placehold.co/96x96/e67e22/fff?text=F%26B",  cats: ["DTC","Food"],        desc: "Better-for-you food brands, meal kits, coffee and ready-to-drink.",                         metrics: { advertisers: "112", shows: "388", avgRoas: "3.1x" } },
    { id: "mental-health", title: "Mental Health",       img: "https://placehold.co/96x96/27ae60/fff?text=MH",     cats: ["Health"],            desc: "Therapy, sleep, meditation and mindfulness apps.",                                          metrics: { advertisers: "42",  shows: "176", avgRoas: "2.4x" } },
    { id: "personal-care", title: "Personal Care",       img: "https://placehold.co/96x96/c0392b/fff?text=PC",     cats: ["DTC","Beauty"],      desc: "Grooming, skincare and beauty brands buying host-read.",                                    metrics: { advertisers: "61",  shows: "208", avgRoas: "3.0x" } },
    { id: "travel",        title: "Travel & Hospitality",img: "https://placehold.co/96x96/2980b9/fff?text=TR",     cats: ["Travel"],            desc: "Booking platforms, airlines, lodging and travel-tech.",                                     metrics: { advertisers: "38",  shows: "144", avgRoas: "2.5x" } },
    { id: "home-sleep",    title: "Home & Sleep",        img: "https://placehold.co/96x96/1a252f/fff?text=HS",     cats: ["Home"],              desc: "Mattresses, sheets, smart-home and sleep technology.",                                      metrics: { advertisers: "47",  shows: "182", avgRoas: "2.9x" } },
  ],
};

window.MARKETPLACE_LABELS = {
  brand:    { metricLabels: ["Avg ROAS", "Annual spend", "Shows live on"],     singular: "brand",    plural: "brands" },
  show:     { metricLabels: ["Listeners / wk", "Avg CPM", "Active advertisers"], singular: "show",     plural: "shows" },
  industry: { metricLabels: ["Advertisers", "Shows", "Avg ROAS"],              singular: "industry", plural: "industries" },
};
