/* ============================================================
   response-leaderboard.data.js
   ------------------------------------------------------------
   The dashboard reads window.LEADERBOARD_DATA from this file.
   It is REGENERATED by the collector — see leaderboard/COLLECTOR.md.
   Do not hand-edit; re-run the collector instead.

   Current snapshot: Slack = live, Email = pending (mailbox not yet connected).
   ============================================================ */
window.LEADERBOARD_DATA = {
  generatedAt: "2026-05-30",
  windowDays: 60,
  cadenceDays: 3,
  sources: { slack: true, email: false },
  sla: { targetHours: 4, warnHours: 12, criticalHours: 24, frustrationMaxHours: 48 },

  team: {
    avgHours: 0.9, medianHours: 0.3, slaHitRate: 97,
    repliesAnalyzed: 69, threadsAnalyzed: 41, openSlow: 4
  },

  people: [
    { name: "Cam Pritchard", handle: "cam@spotsnow.io",   role: "Founder / Ops",   color: "#ff6b6b", avgHours: 0.97, medianHours: 0.50, replies: 31, onTimeRate: 97,  fastest: 0.02, slowest: 5.6, trend: null },
    { name: "Aiza",          handle: "aiza@spotsnow.io",  role: "Account / Media", color: "#4f6ef7", avgHours: 0.86, medianHours: 0.19, replies: 26, onTimeRate: 96,  fastest: 0.01, slowest: 5.9, trend: null },
    { name: "Wally",         handle: "wally@spotsnow.io", role: "Brand / Supply",  color: "#18b368", avgHours: 0.80, medianHours: 0.24, replies: 12, onTimeRate: 100, fastest: 0.01, slowest: 4.0, trend: null },
    { name: "Eli McConkey",  handle: "eli@spotsnow.io",   role: "Ops",             color: "#9a5ad6", na: true, note: "Joined May 30 — baseline pending", replies: 0 }
  ],

  slow: [
    { source: "slack", client: "Super",       channel: "#media-operations", subject: "Super credit — promo-code / cost decision", link: "https://stationpage.slack.com/archives/C09QQ09B0RY", lastTouchBy: "Wally (asked)", waitingOn: "Aiza", gapHours: 5.9 },
    { source: "slack", client: "Super / Amp", channel: "#station-accounts", subject: "Invoice batch — what's left to pay",        link: "https://stationpage.slack.com/archives/C099JM7JCMV", lastTouchBy: "Aiza (posted)", waitingOn: "Cam",  gapHours: 5.6 },
    { source: "slack", client: "Super",       channel: "#station-accounts", subject: "Yap Media — net-terms confirmation",         link: "https://stationpage.slack.com/archives/C099JM7JCMV", lastTouchBy: "Aiza",         waitingOn: "Wally", gapHours: 4.0 },
    { source: "slack", client: "Bleume",      channel: "#media-operations", subject: "Bleume — tracking not showing in dashboard", link: "https://stationpage.slack.com/archives/C09QQ09B0RY", lastTouchBy: "Cam (asked)",  waitingOn: "Aiza", gapHours: 3.8 }
  ],

  clients: [
    { name: "Super",   threads: 22, open: 2, where: "#media-operations · #station-accounts" },
    { name: "Amp",     threads: 9,  open: 2, where: "#media-operations · #station-accounts" },
    { name: "Rella",   threads: 8,  open: 1, where: "#station-accounts · #content-editing" },
    { name: "Bolster", threads: 3,  open: 1, where: "#media-operations · #general" }
  ]
};
