export default async function handler(req, res) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");

  if (req.method === "OPTIONS") return res.status(204).end();
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

  const { brandName, brandWebsite, sections } = req.body || {};
  const brand = brandName || "Brand";
  const website = (brandWebsite || "").replace(/^https?:\/\//, "");
  const today = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  let html = `<html><head><meta charset="utf-8"><style>
body { font-family: Arial, sans-serif; font-size: 11pt; color: #17212b; padding: 32px; }
h1 { font-size: 18pt; margin: 0 0 4px; }
.url { font-size: 10pt; color: #8a95a3; margin: 0 0 24px; }
h2 { font-size: 11pt; margin: 20px 0 6px; padding-bottom: 4px; border-bottom: 1px solid #e8eaed; }
.verbatim { font-size: 8pt; color: #e8474c; background: #fef2f2; padding: 1px 5px; border-radius: 3px; margin-left: 6px; text-transform: uppercase; }
.content { font-size: 10pt; color: #5a6472; line-height: 1.7; white-space: pre-wrap; margin: 0; }
.footer { margin-top: 28px; padding-top: 12px; border-top: 1px solid #e8eaed; font-size: 9pt; color: #8a95a3; }
</style></head><body>
<h1>Talking Points &mdash; ${brand}</h1>
<p class="url">${website}</p>`;

  for (const s of (sections || [])) {
    if (!s.content) continue;
    const vtag = s.verbatim ? '<span class="verbatim">Read Verbatim</span>' : "";
    html += `<h2>${s.label || ""}${vtag}</h2>\n<p class="content">${s.content}</p>\n`;
  }

  html += `<p class="footer">Generated by SpotsNow &middot; ${today}</p></body></html>`;

  const filename = `${brand.replace(/\s+/g, "-")}-talking-points.doc`;
  res.setHeader("Content-Type", "application/msword");
  res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
  return res.status(200).send(html);
}
